spring:
  application:
    name: redis
  redis:
    host: 47.102.203.156
    port: 6379


server:
  port: 6660

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

    register-with-eureka: true






